import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Main from "@/components/main";
import CityNameInput from "@/components/cityNameInput";

export default function Home() {
  const [cityName, setCityName] = useState("Milan");

  function handleCityNameChange(newCityName) {
    setCityName(newCityName);
  }

  return (
    <>
      <Head>
        <title>Pepe's Forecast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <CityNameInput onCityNameChange={handleCityNameChange} />
        <Main cityName={cityName} />
      </main>
    </>
  );
}
